### ISSUE TITLE
Prompting for destination multiple times.

### ISSUE THREAD

**Issue by itsrohanvj** [SahilChachra/ScreenShot-Script#1]
Hi Sahil,
**Great job!** 
Just one small issue. which I found out. It's prompting for the destination when I opt for the wrong choice like 4 or 5 in this  1. screenshot, 2. time-lapse menu. So I suggest you put the dest line outside the while. 
This is really a handy application and I am looking forward to using it in daily usage and add more functionality to it(if possible and time persists).
Cheers!

**Comment by SahilChachra** [comment]
Thanks alot for reporting it. I'll fix it :)

**Comment by SahilChachra** [comment]
It's resolved! Thanks again :D
